version: '3.1'

services:
  db:
    build: ./docker/
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
